name: CI

on:
  push:
    branches: [ master ]
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Ruby for use with actions
      uses: actions/setup-ruby@v1
    - name: Test README.md
      run: |
        gem install awesome_bot
        awesome_bot --allow-dupe --allow-redirect --allow-ssl README.md
